CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GameInfo.Web.Models
{
    public class Company
    {
        [Display(Name = "Company Id")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Company Name")]
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }

        [Display(Name = "Company Szekhely")]
        [Required]
        public string Szekhely { get; set; }

        [Display(Name = "Company Alapitas")]
        [Required]
        public DateTime Alapitas { get; set; }

        [Display(Name = "Company's Boss")]
        [Required]
        public string Boss { get; set; }

        [Display(Name = "Company's MotherCompany")]
        public string MotherCompany { get; set; }

        [Display(Name = "Number of employees")]
        [Required]
        public int Employees { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Models/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameInfo.Web.Models
{
    public class CompanyViewModel
    {
        public Company EditedCompany { get; set; }
        public List<Company> ListOfCompanies { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Controllers/CompaniesController.cs
using AutoMapper;
using GameInfo.Data;
using GameInfo.Logic;
using GameInfo.Repository;
using GameInfo.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static GameInfo.Logic.CegLogic;

namespace GameInfo.Web.Controllers
{
    public class CompaniesController : Controller
    {
        ICegLogic logic;
        IMapper mapper;
        CompanyViewModel vm;

        public CompaniesController()
        {
            GameInfoDBContext ctx = new GameInfoDBContext();
            CegRepository cegRepo = new CegRepository(ctx);
            logic = new CegLogic(cegRepo);
            mapper = MapperFactory.CreateMapper();

            vm = new CompanyViewModel();
            vm.EditedCompany = new Company();
            var companies = logic.GetAllCompanies();
            vm.ListOfCompanies = mapper.Map<IList<Data.Cegek>, List<Models.Company>>(companies);
        }

        private Company GetCompanyModel(int id)
        {
            Cegek oneC = logic.GetOneCeg(id);
            return mapper.Map<Data.Cegek, Models.Company>(oneC);
        }

        // GET: Companies
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CompanyIndex", vm);
        }

        // GET: Companies/Details/5
        public ActionResult Details(int id)
        {
            return View("CompanyDetails", GetCompanyModel(id));
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedCompany = GetCompanyModel(id);
            return View("CompanyIndex", vm);
        }

        // POST: Companies/Edit/5
        [HttpPost]
        public ActionResult Edit(Company comp, string editAction)
        {
            if (ModelState.IsValid && comp != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    /*
                    Cegek newCeg = new Cegek()
                    {
                        Ceg_nev = nev,
                        Szekhely = hely,
                        Fonok = fonok,
                        Anyaceg = anya,
                        Dolgozok_szama = szam,
                        Alapitas = new DateTime(ev, honap, nap),
                    };
                    logic.InsertNewCeg(newCeg);*/
                    //logic.ChangeCompany();

                    
                    logic.InsertNewCeg(new Cegek()
                    {
                        Alapitas = new DateTime(comp.Alapitas.Year, comp.Alapitas.Month, comp.Alapitas.Day),
                        Anyaceg = 2,
                        Ceg_nev = comp.Name,
                        Fonok = comp.Boss,
                        Szekhely = comp.Szekhely,
                        Dolgozok_szama = comp.Employees
                    });
                }
                else
                {
                    bool success = logic.ChangeCompany( 
                        comp.Id,
                        new DateTime(comp.Alapitas.Year, comp.Alapitas.Month, comp.Alapitas.Day),
                        comp.Name,
                        comp.Employees,
                        comp.Boss,
                        comp.Szekhely
                    );
                    if (!success)
                    {
                        TempData["editResult"] = "Edit Fail";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedCompany = comp;
                return View("CompanyIndex", vm);
            }
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            if (logic.RemoveCompany(id))
            {
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Views/Companies/CompanyDetails.cshtml
@model GameInfo.Web.Models.Company
@{
    ViewBag.Title = "CompanyDetails";
}

<h2>Details of one company</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>The ID for the company</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MotherCompany)</td>
        <td>@Html.DisplayFor(m => m.MotherCompany)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Szekhely)</td>
        <td>@Html.DisplayFor(m => m.Szekhely)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Alapitas)</td>
        <td>@Html.DisplayFor(m => m.Alapitas)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Boss)</td>
        <td>@Html.DisplayFor(m => m.Boss)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Employees)</td>
        <td>@Html.DisplayFor(m => m.Employees)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Views/Companies/CompanyEdit.cshtml
@model GameInfo.Web.Models.Company

<h2>Edit one Company</h2>

@using (Html.BeginForm("Edit", "Companies"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-label">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Szekhely)</div>
    <div class="editor-label">@Html.EditorFor(m => m.Szekhely)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Alapitas)</div>
    <div class="editor-label">@Html.EditorFor(m => m.Alapitas)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Boss)</div>
    <div class="editor-label">@Html.EditorFor(m => m.Boss)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Employees)</div>
    <div class="editor-label">@Html.EditorFor(m => m.Employees)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Views/Companies/CompanyIndex.cshtml
@model GameInfo.Web.Models.CompanyViewModel
@{
    ViewBag.Title = "CompanyIndex";
}

<h2>Company Index</h2>
<p style="color: red; font-weight: bold;">@TempData["editResult"]</p>

@Html.Partial("CompanyEdit", Model.EditedCompany)

@Html.Partial("CompanyList", Model.ListOfCompanies)

CSHARP/OENIK_PROG3_2019_2_DTTL84/GameInfo.Web/Views/Companies/CompanyList.cshtml
@model IEnumerable<GameInfo.Web.Models.Company>

<h2>List of companies</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Szekhely)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.Szekhely)</td>
                <td>@Html.ActionLink("[Show]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[Del]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[Edit]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}